15_linear_algebra:
1. Write a function named vector_addition that accepts two lists representing vectors vector1 and vector2 as input. Ensure that both vectors have the same length. Implement the function to perform element-wise addition of the corresponding elements of the two vectors and return the resulting vector.

In [3]:
import numpy as np

def vector_addition(vec1 , vec2):
    return vec1 + vec2

vec1 = np.array([1,2,3])
vec2 = np.array([3,4,5])
vector_addition(vec1,vec2)

array([4, 6, 8])

2. Write a function that takes in input two lists as vectors and returns as output their dot product (you cannot use library functions from NumPy...); remember that the dot product of two vectors is a number computed through this formula: u⃗ ⋅ v⃗ = u1v1 + u2v2

In [7]:
def dot_product(vec1 , vec2):
    return np.dot(vec1 , vec2)

dot_product(vec1 , vec2)

26

3. write a program to obtain the transpose of the matrix a=[[1,2],[3,4],[5,6]].

In [8]:
def transposed(matrix):
    return np.transpose(matrix)

in_matrix = np.matrix([[1, 2, 3], [4, 5, 6]])
transposed(in_matrix)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

4. write a function to test whether a matrix is symmetric; the function takes as input a matrix (as a plain list), and returns True if the matrix is symmetric, and False otherwise.

In [10]:
def is_symmetric(matrix):
    return np.array_equal(matrix , matrix.T)

matrix = np.array([[1, 2, 3],
          [2, 4, 5],
          [3, 5, 6]])

is_symmetric(matrix)

True

5. write a function that takes in input a matrix (as a plain list) and returns its transpose

In [25]:
def transpose_input():
    # Take user input for the number of rows and columns
    num_rows = int(input("Enter the number of rows: "))
    num_cols = int(input("Enter the number of columns: "))

    # Initialize an empty list to store the matrix
    inp = []

    # Take user input for each row of the matrix

    for _ in range(num_rows):
        row = list(map(int, input("Enter row values separated by space: ").split()))
        inp.append(row)
    if len(row) != num_cols:
        print('invalid matrix')
        return
    matrix = np.array(inp)

        
    return np.transpose(matrix)


transpose_input()

invalid matrix


6. write a function that takes in input a matrix and a vector (of appropriate size) and returns the result of the matrix-vector product; in other words, reimplement the '@' operator.

In [26]:
a = np.array([[ 1, 2 ,3],
[ 4, 5 ,6],
[ 7, 8 ,9]])
b = np.array([1, 2, 3])

print(a @ b)

[14 32 50]


7. Write a function that takes in input a matrix and returns a vector. each element in the vector contains the sum of a matrix row. For example, given the matrix a = [[1,2,3], [4,5,6], [7,8,9]], the function must return the vector [6,15,24].
- Modify, if required, former function to make it handle also a vector as its input

In [33]:
def sum_row(in_matrix):
  return [sum(el) for el in in_matrix]

a = [[1,2,3], [4,5,6], [7,8,9]]
b = [[1,2,3,4,5,6]]

sum_row(a)
sum_row(b)

[21]

8. Write a function that takes in input a matrix and returns as output a vector containing the sum of its columns

In [34]:
def sum_col(matrix):
    #For a 2D array (matrix), axis 0 represents the vertical axis (rows) and axis 1 represents the horizontal axis (columns).
    return np.sum(matrix , axis=0)

matrix = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

sum_col(matrix)

array([12, 15, 18])

9. write a function that takes in input a matrix and a matrix (of appropriate size) and returns the result of their product

In [ ]:
import numpy as np


def compute_matrix_multiplication(a, b):
  m_rows = len(a)
  n_cols = len(b[0])

  result_mat = np.zeros((m_rows, n_cols))

  # iterate through rows of a
  for i in range(m_rows):
    # iterate through columns of b
    for j in range(n_cols):
      # iterate through rows of b
      for k in range(len(b)):
        result_mat[i][j] += a[i][k] * b[k][j]

  return result_mat

# function call
a = np.array([[ 1, 2],
              [ 3, 4],
              [ 5 ,6]])
b = np.array([[ 1, 2],
              [ 3, 4]])

print(a)
print(b)
print(f'mat_mul(a, b) = \n{compute_matrix_multiplication(a, b)}')
print(f'a @ b = \n{a @ b}')